name: CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set yml file
        run: |
          mkdir -p ./infinity-api/src/main/resources/application.yml
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: Build with Gradle
        run: ./gradlew :infinity-api:build -x test --parallel

      - name: Build Docker Image For Spring
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/grow:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/grow:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.LINUX_SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker stop grow
            docker rm grow
            docker rmi ${{ secrets.DOCKER_USERNAME }}/grow:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/grow:latest
            docker run -d -p 80:8080 --name grow ${{ secrets.DOCKER_USERNAME }}/grow:latest
